export enum Topic {
  ARTS_CULTURE = 'Arts & Culture',
  BUSINESS_FINANCE = 'Business & Finance',
  CAREERS = 'Careers',
  ENTERTAINMENT = 'Entertainment',
  FASHION_BEAUTY = 'Fashion & Beauty',
  FOOD = 'Food',
  GAMING = 'Gaming',
  HOBBIES_INTERESTS = 'Hobbies & Interests',
  MOVIES_TELEVISION = 'Movies & Television',
  MUSIC = 'Music',
  NEWS = 'News',
  OTHER = 'Other',
  OUTDOORS = 'Outdoors',
  SCIENCE = 'Science',
  SPORTS = 'Sports',
  TECHNOLOGY = 'Technology',
  TRAVEL = 'Travel',
}
